// File generated by FlutterFire CLI.
// This is a placeholder file. Run the following command to generate the actual configuration:
// flutterfire configure --project=brewmaster-coffee

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaOC5ydJCsCZUP7c2Yu1ViPIMZQFCyI5o',
    appId: '1:371292882083:web:fb9003185f59cfb70f6b16',
    messagingSenderId: '371292882083',
    projectId: 'brewmaster-coffee',
    authDomain: 'brewmaster-coffee.firebaseapp.com',
    storageBucket: 'brewmaster-coffee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ZPYxAc9frKh8ZeZdJFLpX1y3BkloVi8',
    appId: '1:371292882083:android:99668219f23b86170f6b16',
    messagingSenderId: '371292882083',
    projectId: 'brewmaster-coffee',
    storageBucket: 'brewmaster-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdIUEkDV4AHZ3YH_inZcfwE-_C88hfYc',
    appId: '1:371292882083:ios:9accfa3c915215cc0f6b16',
    messagingSenderId: '371292882083',
    projectId: 'brewmaster-coffee',
    storageBucket: 'brewmaster-coffee.firebasestorage.app',
    iosBundleId: 'com.brewmaster.brewmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdIUEkDV4AHZ3YH_inZcfwE-_C88hfYc',
    appId: '1:371292882083:ios:9accfa3c915215cc0f6b16',
    messagingSenderId: '371292882083',
    projectId: 'brewmaster-coffee',
    storageBucket: 'brewmaster-coffee.firebasestorage.app',
    iosBundleId: 'com.brewmaster.brewmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaOC5ydJCsCZUP7c2Yu1ViPIMZQFCyI5o',
    appId: '1:371292882083:web:89c408ce5c15a1c50f6b16',
    messagingSenderId: '371292882083',
    projectId: 'brewmaster-coffee',
    authDomain: 'brewmaster-coffee.firebaseapp.com',
    storageBucket: 'brewmaster-coffee.firebasestorage.app',
  );

}